"use client";
import { useState, useEffect } from "react";
import Image from "next/image";
import { Inter } from "next/font/google";
import axios from "axios";

const inter = Inter({ subsets: ["latin"] });

type Message = {
  type: "user" | "bot";
  content: string;
};

export default function Home() {
  const [inputValue, setInputValue] = useState("");
  const [chatLog, setChatLog] = useState<Message[]>([]);
  const [isLoading, setIsLoading] = useState(false);

  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setChatLog((prevChatLog: Message[]) => [
      ...prevChatLog,
      { type: "user", content: inputValue },
    ]);

    generateImage(inputValue);

    setInputValue("");
  };
  const generateImage = async (prompt: string) => {
    setChatLog((prevChatLog: Message[]) => [
      ...prevChatLog,
      {
        type: "bot",
        content:
          "https://oaidalleapiprodscus.blob.core.windows.net/private/org-S4KZYdYIayqtzUwHfdkD7lIX/user-CkSj5QcD2vSaAnIbQJyHDe00/img-tRzDBF6rrL2ceC87JwyRzGNT.png?st=2024-05-22T20%3A32%3A26Z&se=2024-05-22T22%3A32%3A26Z&sp=r&sv=2021-08-06&sr=b&rscd=inline&rsct=image/png&skoid=6aaadede-4fb3-4698-a8f6-684d7786b067&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2024-05-22T10%3A37%3A46Z&ske=2024-05-23T10%3A37%3A46Z&sks=b&skv=2021-08-06&sig=MFDmc01DkF0%2Brzy1d7inblRkaB986DHDdWSJQWv590E%3D",
      },
    ]);
    // setIsLoading(true);
    // const response = await fetch("/api/generate-image", {
    //   method: "POST",
    //   headers: {
    //     "Content-Type": "application/json",
    //   },
    //   body: JSON.stringify({ prompt: prompt }),
    // });
    // if (response.ok) {
    //   const data = await response.json();
    //   setChatLog((prevChatLog: Message[]) => [
    //     ...prevChatLog,
    //     { type: "bot", content: data.image_url },
    //   ]);
    //   setIsLoading(false);
    // } else {
    //   console.error("Error generating image:", response.statusText);
    // }
  };

  return (
    <>
      <h1>Image Chat</h1>
      {chatLog.map((message, index) => (
        <div key={index}>
          {message.type === "user" ? "You: " + message.content : "ChatGPT: "}
          {message.type === "bot" && (
            <Image
              src={message.content}
              alt="Generated by DALL-E"
              width="256"
              height="256"
            />
          )}
        </div>
      ))}
      <form onSubmit={handleSubmit}>
        <input
          type="text"
          placeholder="Describe your image..."
          value={inputValue}
          onChange={(e) => setInputValue(e.target.value)}
        />
        <button type="submit">Send</button>
      </form>
    </>
  );
}
